--- 
- hosts: acs-manager
  roles: 
    - mysql
    - nfs-server
    - cloudstack-manager
    - cloudmonkey
    - cloudstack-agent
    - openvswitch
  tasks: 
    - include: ./roles/cloudstack-manager/tasks/seedstorage.yml
  vars: 
    - mysql_root_password: Cl0ud5tack
    - mysql_cloud_password: Cl0ud5tack
    - baseurl_cloudstack: "http://download.cloudstack.org/centos/7/4.11/"
    - old_mysql_root_password: ""
    - systemvm_templates: 
      - { url: 'http://download.cloudstack.org/systemvm/4.11/systemvmtemplate-4.11.1-kvm.qcow2.bz2', hypervisor: 'kvm' }
      - { url: 'http://download.cloudstack.org/systemvm/4.11/systemvmtemplate-4.11.1-vmware.ova', hypervisor: 'vmware' }
      - { url: 'http://download.cloudstack.org/systemvm/4.11//systemvmtemplate-4.11.1-xen.vhd.bz2', hypervisor: 'xenserver' }
